# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_name', models.CharField(max_length=128)),
                ('ecs_id', models.CharField(max_length=128)),
                ('status', models.BooleanField(default='0')),
                ('regoin', models.CharField(max_length=32)),
                ('shut_time', models.DateField(auto_now_add=True)),
                ('task_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_name', models.CharField(max_length=128)),
                ('ecs_id', models.CharField(max_length=128)),
                ('status', models.BooleanField(default='0')),
                ('region', models.CharField(max_length=32)),
                ('shut_time', models.DateField(auto_now_add=True)),
                ('task_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('region', models.CharField(default='cn-north-1a', max_length=32)),
                ('up_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_name', models.CharField(default='hostname', max_length=128)),
                ('region', models.CharField(default='cn-north-1a', max_length=32)),
                ('ecs_late_time', models.DateField(auto_now_add=True, verbose_name='例外结束时间')),
                ('submitter', models.CharField(default='admin', max_length=128, verbose_name='提交人')),
                ('ecs_id', models.CharField(default='123', max_length=128)),
                ('sub_time', models.DateField(auto_now=True, verbose_name='提交时间')),
                ('ex_time', models.CharField(default=['6hours', '12hours', '24hours', 'forever'], max_length=32)),
                ('tag', models.BooleanField(default='0')),
            ],
        ),
    ]
