# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='up_time',
            field=models.DateField(auto_now=True, max_length=128),
        ),
    ]
