# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20170801_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='shut_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='task_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tmp',
            name='shut_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tmp',
            name='task_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='ecs_late_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='例外结束时间'),
        ),
        migrations.AlterField(
            model_name='web',
            name='sub_time',
            field=models.DateTimeField(auto_now=True, verbose_name='提交时间'),
        ),
    ]
