# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20170801_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_name', models.CharField(default='hostname', max_length=128, verbose_name='主机名')),
                ('region', models.CharField(default='cn-north-1', max_length=32, verbose_name='区域')),
                ('ecs_last_time', models.DateTimeField(auto_now_add=True, verbose_name='关机时间')),
                ('submitter', models.CharField(default='admin', max_length=128, verbose_name='提交人')),
                ('ecs_id', models.CharField(default='123', max_length=128, verbose_name='主机ID')),
                ('sub_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('ex_time', models.CharField(default=['3', '6', '9', '12', '24', 'forever'], max_length=32, verbose_name='保留时间(h)')),
                ('tag', models.BooleanField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Ecs_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_name', models.CharField(max_length=128)),
                ('ecs_id', models.CharField(max_length=128)),
                ('status', models.BooleanField()),
                ('region', models.CharField(max_length=32)),
                ('shut_time', models.DateTimeField(null=True)),
                ('delete_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Tmp',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
        migrations.AlterField(
            model_name='token',
            name='region',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='token',
            name='up_time',
            field=models.DateTimeField(),
        ),
    ]
