# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_auto_20170803_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs_all',
            name='status',
        ),
        migrations.AddField(
            model_name='ecs_all',
            name='operate',
            field=models.BooleanField(default='1'),
        ),
    ]
