# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_auto_20170808_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='ecs_id',
            field=models.CharField(max_length=128, verbose_name='主机ID'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_name',
            field=models.CharField(max_length=128, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='region',
            field=models.CharField(max_length=32, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='submitter',
            field=models.CharField(max_length=128, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='tag',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='ecs_all',
            name='operate',
            field=models.BooleanField(default=1),
        ),
    ]
