# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_auto_20170808_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='tag',
            new_name='operate',
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_id',
            field=models.CharField(default='例如：c90ab83a-6cdd-4404-8578-05fa965cfb12', max_length=128, verbose_name='主机ID'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_name',
            field=models.CharField(default='例如：dwx411174_test', max_length=128, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='region',
            field=models.CharField(default='例如：cn-north-1', max_length=32, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='submitter',
            field=models.CharField(default='填写工号，例如：dwx411174', max_length=128, verbose_name='提交人'),
        ),
    ]
