# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_auto_20170808_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs',
            name='ex_time',
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_last_time',
            field=models.DateTimeField(verbose_name='关机时间'),
        ),
    ]
