# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_auto_20170808_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs',
            name='operate',
        ),
    ]
