# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0015_auto_20170809_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='ecs_last_time',
            new_name='ecs_shut_time',
        ),
        migrations.RemoveField(
            model_name='ecs',
            name='sub_time',
        ),
        migrations.RemoveField(
            model_name='ecs',
            name='submitter',
        ),
        migrations.AddField(
            model_name='ecs',
            name='delete_ecs_tag',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='ecs',
            name='shut_ecs_tag',
            field=models.BooleanField(default=1),
        ),
    ]
