# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_auto_20170810_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='ecs_status_tag',
            field=models.BooleanField(default=1),
        ),
    ]
