# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0020_auto_20170810_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecs_all',
        ),
        migrations.AlterField(
            model_name='ecs',
            name='delete_ecs_tag',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_status_tag',
            field=models.BooleanField(default=0, verbose_name='是否运行中'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='shut_ecs_tag',
            field=models.BooleanField(default=0, verbose_name='是否关机'),
        ),
    ]
