# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0021_auto_20170811_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='ecs_status_tag',
            field=models.BooleanField(default=0, verbose_name='是否开机'),
        ),
    ]
