# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0022_auto_20170811_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='delete_ecs_tag',
            field=models.BooleanField(default=0, verbose_name='删除'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_status_tag',
            field=models.BooleanField(default=0, verbose_name='运行中'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='shut_ecs_tag',
            field=models.BooleanField(default=0, verbose_name='关机'),
        ),
    ]
