# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0023_auto_20170811_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='account_name',
            field=models.CharField(default='hwclouds', max_length=20, null=True, verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_id',
            field=models.CharField(default='例：c90ab83a-6cdd-4404-8578-05fa965cfb12', max_length=40, primary_key=True, serialize=False, verbose_name='主机ID'),
        ),
    ]
