# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0024_auto_20170811_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='account_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='account_name',
            field=models.CharField(max_length=20, null=True, verbose_name='账户'),
        ),
    ]
