# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0025_auto_20170811_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='account_name',
            field=models.CharField(default='例：hwclouds', max_length=20, primary_key=True, serialize=False),
        ),
    ]
