# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0026_auto_20170822_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecs',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
