# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0028_ecs_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='region',
            field=models.CharField(choices=[('cn-north-1', '华北1'), ('cn-south-1', '华南1'), ('cn-east-2', '华东2')], default='cn-north-1', max_length=32, verbose_name='区域'),
        ),
    ]
