# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwaccount', '0002_auto_20170821_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账户名'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pid_north1',
            field=models.CharField(default='在我的凭证中查看项目列表获取', max_length=40, verbose_name='项目ID-华北1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(default='若使用帐户名登录，此项填写账户名', max_length=20, verbose_name='用户名'),
        ),
    ]
