# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwaccount', '0003_auto_20170821_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
