# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwaccount', '0004_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账户名')),
                ('user_name', models.CharField(default='若使用帐户名登录，此项填写账户名', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('pid_north1', models.CharField(default='在我的凭证中查看项目列表获取', max_length=40, verbose_name='项目ID-华北1')),
                ('pid_east2', models.CharField(max_length=40, verbose_name='项目ID-华东2')),
                ('pid_south1', models.CharField(max_length=40, verbose_name='项目ID-华南1')),
            ],
        ),
    ]
