# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwaccount', '0005_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pid_east2',
            new_name='pidcn_east_2',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='pid_north1',
            new_name='pidcn_north_1',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='pid_south1',
            new_name='pidcn_south_1',
        ),
    ]
